# Generated by Django 5.2.10 on 2026-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliveryconfig_product_quantity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Available inventory'),
        ),
    ]
