# Generated by Django 5.2.13 on 2026-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
